# Generated by Django 4.2.4 on 2023-09-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=100)),
                ('experiencia', models.TextField()),
                ('habilidades', models.TextField()),
                ('educacion', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('vacante', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
    ]
